### ISSUE TITLE
[Data] upcoming-ipos

### ISSUE THREAD

**Issue by MorningSleeper** [iexg/IEX-API#1108]
When I access https://sandbox.iexapis.com/beta/stock/market/upcoming-ipos?token=... in my browser it looks fine and validates but when I retrieve it in node.js (ver. 10.16.0) using the example code in docs at https://iexcloud.io/docs/api/#getting-the-secret-for-a-signed-token the line reading `var parsed = JSON.parse(chunk)`; causes the following error. Any idea why?

```
07-10-2019 05:04:37.8 [ERROR] Uncaught Exception Error:
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/webserver/sites/commands/ipos.js:56:29)
    at IncomingMessage.emit (events.js:198:13)
    at IncomingMessage.Readable.read (_stream_readable.js:491:10)
    at flow (_stream_readable.js:957:34)
    at resume_ (_stream_readable.js:938:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
07-10-2019 05:04:37.8 [ERROR] Uncaught Exception Error:
SyntaxError: Unexpected token , in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/webserver/sites/commands/ipos.js:56:29)
    at IncomingMessage.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:265:13)
    at IncomingMessage.Readable.push (_stream_readable.js:224:10)
    at HTTPParser.parserOnBody (_http_common.js:122:22)
    at TLSSocket.socketOnData (_http_client.js:442:20)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
07-10-2019 05:04:37.9 [ERROR]
{
   "bytesParsed": 0,
   "code": "HPE_CB_body"
}
```

[json.txt](https://github.com/iexg/IEX-API/files/3377408/json.txt)

**Comment by MorningSleeper** [comment]
Was able to get it to work by changing the example code in API docs. According to post below ...

"Note if you are using https.request do not directly use the body from res.on('data',... This will fail if you have a large data coming in chunks. So you need to concatenate all the data and then process the response in res.on('end'

[https://stackoverflow.com/a/51783577/2780335](url)

So the following from API docs does not work in this case.

```
const req = https.request(options, function (res) {

  res.setEncoding('utf8');

  res.on('data', function (chunk) {
    var parsed = JSON.parse(chunk); // error
  });

});

req.end();
```

But the following does work.

```
 const req = https.request(options, function (res) {

       res.setEncoding('utf8');
       var body = '';

       res.on('data', function (chunk) {
         body = body + chunk;
       });

       res.on('end', function () {
         var parsed = JSON.parse(body); // works
         parsed.viewData[0].Company; // works
       });
     
 });
```
