### ISSUE TITLE
iexfinance.utils.exceptions.IEXQueryError

### ISSUE THREAD

**Issue by anay2103** [iexg/IEX-API#1257]
I'm having an issue with Python SDK. When running a Read-me code example i'm getting iexfinance.utils.exceptions.IEXQueryError
I'm working with Sandbox regime and have my tsk secret token set as an env. variable.
An equivalent curl quote gets  fine response.
Any help would be appreciated.

Version: Python 3.6.

**date of issue**
2019-09-25

**expected behavior**
Hoping for getting stock balance sheet data

**actual behavior**

 ```
>>> from iexfinance.stocks import Stock
>>> aapl = Stock("AAPL")
>>> aapl.get_balance_sheet()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\iexfinance\stocks\base.py", line 193, in get_balance_sheet
    return self._get_endpoint("balance-sheet", fmt_p=fmt_p, params=kwargs)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\iexfinance\stocks\base.py", line 103, in _get_endpoint
    data = self.fetch(fmt_j=fmt_j, fmt_p=no_pandas)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\iexfinance\base.py", line 209, in fetch
    data = self._execute_iex_query(url)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\iexfinance\base.py", line 165, in _execute_iex_query
    return self._handle_error(response)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python36\lib\site-packages\iexfinance\base.py", line 178, in _handle_error
    raise IEXQueryError("The query could not be completed. "
iexfinance.utils.exceptions.IEXQueryError: An error occurred while making the query.`

**Comment by McQgit** [comment]
@anay2103  Given the curl works it may well be something unique to the iexfinance python module.  You might want to have look at this topic:  []https://github.com/iexg/IEX-API/issues/1254

**Comment by anay2103** [comment]
**McQgit** Thanks for your reply. It urged me to read the the docs once more and find a solution. I was so inattentive! Sorry to have put dumb questions here.
