### ISSUE TITLE
iex request does not work

### ISSUE THREAD

**Issue by izzyprad** [iexg/IEX-API#1287]
I am able to run this:
```

os.environ['IEX_API_VERSION'] = 'iexcloud-beta'
os.environ['IEX_TOKEN'] = 'xxxxx'
from iexfinance.stocks import Stock
Stock("AAPL").get_quote()
Stock("AAPL").get_historical_prices()
```

but none of the following line works:
```
Stock("AAPL").get_price()
Stock("AAPL").get_balance_sheet()
Stock("AAPL").get_income_statement()
```

Any idea?

I get this error:
```
Traceback (most recent call last):
  File "<pyshell#21>", line 1, in <module>
    Stock("AAPL").get_income_statement()
  File "C:\Users\IzzY\AppData\Local\Programs\Python\Python37-32\lib\site-packages\iexfinance\stocks\base.py", line 514, in get_income_statement
    params=kwargs)
  File "C:\Users\IzzY\AppData\Local\Programs\Python\Python37-32\lib\site-packages\iexfinance\stocks\base.py", line 103, in _get_endpoint
    data = self.fetch(fmt_j=fmt_j, fmt_p=no_pandas)
  File "C:\Users\IzzY\AppData\Local\Programs\Python\Python37-32\lib\site-packages\iexfinance\base.py", line 209, in fetch
    data = self._execute_iex_query(url)
  File "C:\Users\IzzY\AppData\Local\Programs\Python\Python37-32\lib\site-packages\iexfinance\base.py", line 165, in _execute_iex_query
    return self._handle_error(response)
  File "C:\Users\IzzY\AppData\Local\Programs\Python\Python37-32\lib\site-packages\iexfinance\base.py", line 178, in _handle_error
    raise IEXQueryError("The query could not be completed. "
iexfinance.utils.exceptions.IEXQueryError: An error occurred while making the query.
```

**Comment by joshuablackburn-iex** [comment]
You may need to reach out to the maintainer of the library.  https://github.com/addisonlynch/iexfinance
