### ISSUE TITLE
get_collections("Industrials", output_format='pandas').head() Error

### ISSUE THREAD

**Issue by raeldor** [iexg/IEX-API#1468]
### Please keep all posted issues professional and constructive. We may delete posts that do not provide sufficient information, are outright negative and unproductive, or are not directly related to IEX Cloud.

**Clearly describe the problem**

executing the sample...

get_collections("Industrials", output_format='pandas').head()

results in the error...

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Ray\Anaconda3\envs\tensorflow\lib\site-packages\iexfinance\stocks\__init__.py", line 107, in get_collections
    collection_type, **kwargs).fetch()
  File "C:\Users\Ray\Anaconda3\envs\tensorflow\lib\site-packages\iexfinance\base.py", line 210, in fetch
    return self._output_format(data, fmt_j=fmt_j, fmt_p=fmt_p)
  File "C:\Users\Ray\Anaconda3\envs\tensorflow\lib\site-packages\iexfinance\base.py", line 224, in _output_format
    return self._convert_output(out)
  File "C:\Users\Ray\Anaconda3\envs\tensorflow\lib\site-packages\iexfinance\stocks\collections.py", line 35, in _convert_output
    return pd.DataFrame(out).set_index("symbol").T
  File "C:\Users\Ray\Anaconda3\envs\tensorflow\lib\site-packages\pandas\core\frame.py", line 4411, in set_index
    raise KeyError("None of {} are in the columns".format(missing))
KeyError: "None of ['symbol'] are in the columns"

**What time did the problem occur? (with timezone)**
May 6th 2020, 3:46PM JST.

**What is the expected behavior?**

Return a list.

**Your environment (e.g. browser, OS, API version, language):**

Windows 10, python, anaconda.

**API URL (if applicable)**

**What are the steps to reproduce the bug?**

Just import and execute the sample

**Additional context**

**Comment by McQgit** [comment]
A number of people struggle using that iexfinance python app. It was not developed (and not supported by) the IEX folks. See this prior topic for where to find help for iexfinance: https://github.com/iexg/IEX-API/issues/1257

**Comment by addisonlynch** [comment]
Hello, developer of ``iexfinance`` here. This issue has been resolved in ``iexfinance``, however is no tag collection for Industrials in IEX Cloud. 

Try:

```python3
get_collections("Technology", "sector", output_format='pandas')
```

Please open an issue at https://github.com/addisonlynch/iexfinance if you have any further issues. Thanks!
